# Generated by Django 3.2.16 on 2022-10-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', '-created_date']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='complete',
        ),
    ]
